### ISSUE TITLE
Issue to compilation

### ISSUE THREAD

**Issue by hdeselys** [exo-addons/extension-generator#1]
I tried to compile the extension generator and I came to an error. It seems that some argument is missing in the call of ManagedResponse.writeResult() in the file AbstractConfigurationHandler.java (extension-generator-master/service/src/main/java/org/exoplatform/extension/generator/service/api/AbstractConfigurationHandler.java). The method needs two arguments (OutputStream outputStream, boolean pretty) but only one is provided in the code, the first one. So the boolean argument is missing, I guess.
Best regards.

**Comment by boubaker** [comment]
The third party framework GateIN Management was modified in Staging Extension Snapshot.
Fixed.
Thank you for reporting.
